import {
  CustomHttpResponse,
  ILaunchPad,
} from 'src/app/core/model/launchpad.model';

export const MockRegionsList: string[] = [
  'Region 1',
  'Region 2',
  'Region 3',
  'Region 4',
  'Region 5',
  'Region 6',
];
export const mockLaunchPAdList: ILaunchPad[] = [
  {
    id: '1',
    full_name: 'LaunchPad 1',
    region: MockRegionsList[0],
    wikipedia: 'http://wikip1.com',
    launches: [],
  },
  {
    id: '2',
    full_name: 'LaunchPad 2',
    region: MockRegionsList[0],
    wikipedia: 'http://wikip1.com',
    launches: [],
  },
  {
    id: '3',
    full_name: 'LaunchPad 3',
    region: MockRegionsList[1],
    wikipedia: 'http://wikip1.com',
    launches: [],
  },
  {
    id: '4',
    full_name: 'LaunchPad 4',
    region: MockRegionsList[1],
    wikipedia: 'http://wikip1.com',
    launches: [],
  },
  {
    id: '5',
    full_name: 'LaunchPad 5',
    region: MockRegionsList[2],
    wikipedia: 'http://wikip1.com',
    launches: [],
  },
  {
    id: '6',
    full_name: 'LaunchPad 6',
    region: MockRegionsList[2],
    wikipedia: 'http://wikip1.com',
    launches: [],
  },
  {
    id: '7',
    full_name: 'LaunchPad 7',
    region: MockRegionsList[3],
    wikipedia: 'http://wikip1.com',
    launches: [],
  },
  {
    id: '8',
    full_name: 'LaunchPad 8',
    region: MockRegionsList[3],
    wikipedia: 'http://wikip1.com',
    launches: [],
  },
  {
    id: '9',
    full_name: 'LaunchPad 9',
    region: MockRegionsList[4],
    wikipedia: 'http://wikip1.com',
    launches: [],
  },
  {
    id: '10',
    full_name: 'LaunchPad 10',
    region: MockRegionsList[4],
    wikipedia: 'http://wikip1.com',
    launches: [],
  },
  {
    id: '11',
    full_name: 'LaunchPad 11',
    region: MockRegionsList[5],
    wikipedia: 'http://wikip1.com',
    launches: [],
  },
  {
    id: '12',
    full_name: 'LaunchPad 12',
    region: MockRegionsList[5],
    wikipedia: 'http://wikip1.com',
    launches: [],
  },
];
export const MockData: CustomHttpResponse<ILaunchPad> = {
  docs: mockLaunchPAdList,
  limit: 5,
  offset: 0,
  page: 1,
  totalDocs: mockLaunchPAdList.length,
  totalPages: mockLaunchPAdList.length / 5,
  hasNextPage: true,
  hasPrevPage: false,
  nextPage: null,
  pagingCounter: 1,
  prevPage: null,
};
